version: '3.1'

services:

  mysql:
    container_name: mysql
    image: mysql:8.0.32
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - mysql_msvc_usuarios:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: msvc_usuarios
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=example --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10
    networks:
      - spring

  msvc-usuarios:
    container_name: msvc-usuarios
    depends_on:
      mysql:
        condition: service_healthy
    image: pblgllgs/msvc-usuarios:0.0.6
    restart: always
    ports:
      - "8001:8001"
    environment:
      PORT: 8001
      DB_HOST: mysql:3306
      DB_DATABASE: msvc_usuarios
      DB_USERNAME: root
      DB_PASSWORD: example
      CURSOS_URL: <INSTANCE_IP/DNS_NAME>:8002
    networks:
      - spring

volumes:
  mysql_msvc_usuarios:
    external: false

networks:
  spring: