apiVersion: v1
kind: ConfigMap
metadata:
  name: msvc-usuarios
data:
  port: "8001"
  db_host: "mysql:3306"
  database: msvc_usuarios
  username: root
  password: example
  cursos_url: "msvc-cursos:8002"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: msvc-cursos
data:
  port: "8002"
  db_host: "postgres:5432"
  database: msvc_cursos
  username: postgres
  password: example
  usuarios_url: "msvc-usuarios:8001"