apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0.32
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 250m
            memory: 500Mi
        ports:
        - containerPort: 3306
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: msvc-usuarios
                key: username
          - name: MYSQL_DATABASE
            valueFrom:
              configMapKeyRef:
                name: msvc-usuarios
                key: database
        volumeMounts:
          - name: data-mysql
            mountPath: /var/lib/mysql

      volumes:
        - name: data-mysql
          persistentVolumeClaim:
            claimName: mysql-pvc
