apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15.1
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 250m
            memory: 500Mi
        ports:
        - containerPort: 5432
        env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: msvc-cursos
                key: username
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: msvc-cursos
                key: password
          - name: POSTGRES_DB
            valueFrom:
              configMapKeyRef:
                name: msvc-cursos
                key: database
        volumeMounts:
          - name: data-postgres
            mountPath: /var/lib/postgresql/data

      volumes:
        - name: data-postgres
          persistentVolumeClaim:
            claimName: postgres-pvc