apiVersion: apps/v1
kind: Deployment
metadata:
  name: msvc-cursos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: msvc-cursos
  template:
    metadata:
      labels:
        app: msvc-cursos
    spec:
      containers:
      - name: msvc-cursos
        image: pblgllgs/msvc-cursos:0.0.7
        ports:
        - containerPort: 8002
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 250m
            memory: 500Mi
        env:
          - name: PORT
            value: "8002"
          - name: DB_HOST
            value: "postgres:5432"
          - name: DB_DATABASE
            value: msvc_cursos
          - name: DB_USERNAME
            value: postgres
          - name: DB_PASSWORD
            value: example
          - name: USUARIOS_URL
            value: "msvc-usuarios:8001"
