apiVersion: apps/v1
kind: Deployment
metadata:
  name: msvc-cursos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: msvc-cursos
  template:
    metadata:
      labels:
        app: msvc-cursos
    spec:
      containers:
      - name: msvc-cursos
        image: pblgllgs/msvc-cursos:0.1.0
        ports:
        - containerPort: 8002
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 350m
            memory: 500Mi
        env:
          - name: PORT
            valueFrom:
              configMapKeyRef:
                name: msvc-cursos
                key: port
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: msvc-cursos
                key: db_host
          - name: DB_DATABASE
            valueFrom:
              configMapKeyRef:
                name: msvc-cursos
                key: database
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: msvc-cursos
                key: username
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: msvc-cursos
                key: password
          - name: USUARIOS_URL
            valueFrom:
              configMapKeyRef:
                name: msvc-cursos
                key: usuarios_url
