apiVersion: apps/v1
kind: Deployment
metadata:
  name: msvc-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: msvc-auth
  template:
    metadata:
      labels:
        app: msvc-auth
    spec:
      containers:
      - name: msvc-auth
        image: pblgllgs/msvc-auth:0.0.4-sas1.0.0-c1
        ports:
        - containerPort: 9000
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 350m
            memory: 500Mi
        env:
          - name: LB_USUARIOS_URI
            valueFrom:
              configMapKeyRef:
                name: msvc-usuarios
                key: lb_usuarios_uri
            
---
apiVersion: v1
kind: Service
metadata:
  name: msvc-auth
spec:
  ports:
  - port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: msvc-auth
  type: LoadBalancer